LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := RemovePackages
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_OVERRIDES_PACKAGES := PartnerSetupPrebuilt
LOCAL_OVERRIDES_PACKAGES += SafetyHubPrebuilt SecurityHubPrebuilt
LOCAL_OVERRIDES_PACKAGES += GoogleFeedback HelpRtcPrebuilt
LOCAL_OVERRIDES_PACKAGES += Camera2
LOCAL_OVERRIDES_PACKAGES += SoundAmplifierPrebuilt PixelBuds
LOCAL_OVERRIDES_PACKAGES += GoogleTTS
LOCAL_UNINSTALLABLE_MODULE := true
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_SRC_FILES := /dev/null
include $(BUILD_PREBUILT)
